[build]
  Command = "bundle exec jekyll build --source . --destination ./_site"
  Publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
